version: "2"
services:
  mysql:
    image: mariadb
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=CHANGE_ME_IM_NOT_SECURE
      - MYSQL_DATABASE=phpservermon
    expose:
      - 3306

  phpservermon:
    build: .
    container_name: phpservermon
    depends_on:
      - mysql
    environment:
      - PSM_TIMEZONE=Europe/Paris
      - PSM_BASE_URL=
      - PSM_DB_HOST=mysql
      - PSM_DB_PORT=3306
      - PSM_DB_NAME=phpservermon
      - PSM_DB_USER=root
      - PSM_DB_PASS=CHANGE_ME_IM_NOT_SECURE
      - PSM_DB_PREFIX=
      - UPDATE_INTERVAL=15
    ports:
      - "8081:80"
